# Generated by Django 3.2.13 on 2022-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorsites', '0002_alter_monitorsite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsite',
            name='last_polled_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorsite',
            name='ssl_expirtaion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorsite',
            name='ssl_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
