# Generated by Django 3.2.13 on 2022-06-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorsites', '0003_auto_20220610_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorsite',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='monitorsite',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
