# Generated by Django 3.2.13 on 2022-06-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorsites', '0004_auto_20220611_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSiteEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255)),
                ('url_message', models.CharField(blank=True, max_length=255)),
                ('ssl_expirtaion', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(blank=True, max_length=255)),
                ('ssl_message', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorsites.monitorsite')),
            ],
        ),
    ]
